version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - Installing app dependencies...
      - yarn install
  build:
    commands:
      - Building static site...
      - yarn build

artifacts:
  type: zip
  files:
    - '**/*'
  base-directory: 'build'

cache:
  paths:
    - './node_modules/**/*'
