version: "3"

services:
  server:
    image: node:12
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3000
    environment:
      - PORT=3000
    command: sh -c "npm install && npm run dev"
